# Generated by Django 4.0 on 2022-11-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_marriage_marriagecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdata',
            name='Gender',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
