# Generated by Django 4.1 on 2022-11-12 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userdata_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marriage',
            name='Spousename',
        ),
    ]
