# Generated by Django 4.1 on 2022-11-12 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_marriage_spousename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='Spousecid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdata'),
        ),
    ]
