# Generated by Django 4.1 on 2022-11-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_marriage_spousecid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='childdata',
        ),
    ]
