# Generated by Django 4.1 on 2022-11-14 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_marriage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='your_cid',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='you', to='accounts.userdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marriage',
            name='Spousecid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spouce', to='accounts.userdata'),
        ),
    ]
